name: waka-data-collect-and-statistics

# 事件触发
on:
  # 手动触发
  workflow_dispatch:
  # 定时任务
  schedule:
    # 09:00:00 +08
    - cron: '0 1 * * *'

# 执行的任务
jobs:
  start:
    # 操作系统
    runs-on: ubuntu-latest
    # 步骤
    steps:
      # 代码
      - name: checkout
        uses: actions/checkout@v2
        with:
          # 指定分支
          ref: 'main'
      # 设置jdk
      - name: set up jdk 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          java-package: jdk
          architecture: x64
      # 缓存加速
      - name: use cache to speed up the time of build
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      # 运行代码
      - name: execute the task
        # env:
        #   WAKA_API_KEY: ${{ secrets.WAKA_API_KEY }}
        #   OSS_ENDPOINT: ${{ secrets.OSS_ENDPOINT }}
        #   OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
        #   OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
        #   OSS_BUCKET_NAME: ${{ secrets.OSS_BUCKET_NAME }}
        run: >
          ./gradlew run --args='
          --wakaApiKey ${{ secrets.WAKA_API_KEY }}
          --ossEndpoint ${{ secrets.OSS_ENDPOINT }}
          --ossAccessKeyId ${{ secrets.OSS_ACCESS_KEY_ID }}
          --ossAccessKeySecret ${{ secrets.OSS_ACCESS_KEY_SECRET }}
          --ossBucketName ${{ secrets.OSS_BUCKET_NAME }}
          '
