# https://docs.github.com/en/actions

name: waka-data-collect-and-statistics

# 事件触发
on:
  # 手动触发
  workflow_dispatch:
  # 定时任务
  schedule:
    # 08:00:00 +08
    - cron: '0 0 * * *'

# 执行的任务
jobs:
  start:
    # 操作系统
    runs-on: ubuntu-latest
    # 步骤
    steps:
      # 代码
      # https://github.com/marketplace/actions/checkout
      # https://github.com/actions/checkout
      - name: checkout
        uses: actions/checkout@v2
        with:
          # 指定分支
          ref: 'statistics_support'
      # 设置 jdk
      # https://github.com/marketplace/actions/setup-java-jdk
      # https://github.com/actions/setup-java
      - name: set up jdk 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          java-package: jdk
          distribution: adopt
          architecture: x64
          # cache: gradle
      # 设置 nodejs
      # https://github.com/marketplace/actions/setup-node-js-environment
      # https://github.com/actions/setup-node
      - name: set up nodejs 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          # cache: npm
      # 缓存加速
      # https://github.com/marketplace/actions/cache
      # https://github.com/actions/cache
      - name: use cache to speed up the time of build for gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: use cache to speed up the time of build for nodejs
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ~/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json', '**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      # 运行代码
      # https://github.com/marketplace/actions/run-on-architecture
      - name: execute the task
        # env:
        #   WAKA_API_KEY: ${{ secrets.WAKA_API_KEY }}
        #   OSS_ENDPOINT: ${{ secrets.OSS_ENDPOINT }}
        #   OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
        #   OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
        #   OSS_BUCKET_NAME: ${{ secrets.OSS_BUCKET_NAME }}
        # working-directory: '~'
        run: >
          npm install &&
          ./gradlew run --args='
          --wakaApiKey ${{ secrets.WAKA_API_KEY }}
          --ossEndpoint ${{ secrets.OSS_ENDPOINT }}
          --ossAccessKeyId ${{ secrets.OSS_ACCESS_KEY_ID }}
          --ossAccessKeySecret ${{ secrets.OSS_ACCESS_KEY_SECRET }}
          --ossBucketName ${{ secrets.OSS_BUCKET_NAME }}
          --dingRobotWebhook ${{ secrets.DING_ROBOT_WEBHOOK }}
          --reportHomeUrl ${{ secrets.REPORT_HOME_URL }}
          '
      # add commit & push
      # https://github.com/marketplace/actions/git-commit-and-push
      - name: push changes
        uses: github-actions-x/commit@v2.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: ${{ github.ref }}
          commit-message: 'Actions Generated'
          force-add: 'true'
          files: docs/
          name: manerfan
          email: manerfan@163.com
